Separate relations into separate yaml document
canonical/stsstack-bundles pull request #156
Opened 2023-11-21 02:33 UTC by rafalop

To adjust to new juju 3.2 behaviour that does not
allow relations referencing overlay applications
in the base bundle.

Ref: https://bugs.launchpad.net/juju/+bug/2041785

Resolves: #149

2023-11-23 01:16 UTC, rafalop commented
FYI this change is compatible with older juju versions (ie 2.x).

2023-11-27 20:59 UTC, nicolasbock requested changes
Neat that the fix is so simple :smile:

2023-11-27 20:59 UTC, nicolasbock commented on tools/juju-bundle-applications.py
The `yaml.load_all()` function returns a list of documents:
```suggestion
        for d in data:
            if 'applications' in d:
                application_list.update(d['applications'].keys())
```

2023-11-28 16:49 UTC, nicolasbock approved these changes

2023-11-28 17:21 UTC, merged

2024-06-14 06:38 UTC, lathiat commented
I only just caught up on this one and just wanted to note that using --- to start a new yaml document within the same file is a fantastic hack. 

I had solved this in my local branch by deploying an overlay/blank.yaml as the base bundle, and then passing in the real base bundle (e.g. openstack.yaml) as the first overlay.