Change systemd-resolve for resolvectl
canonical/stsstack-bundles pull request #172
Opened 2024-02-21 13:32 UTC by drencrom

The `systemd-resolve` tool has been renamed to `resolvectl` in [systemd 239](https://github.com/systemd/systemd/blob/main/NEWS#L8539). 
From Jammy onwards the symlink `systemd-resolve` has been deleted and this code does not work.
Focal has systemd 245 so this change in fact removes support for Bionic and adds support for Jammy and following releases. If support for Bionic is still desired the patch should be expanded.

2024-02-21 15:20 UTC, nicolasbock commented
Thanks for the fix!

We are supporting Bionic / Queens until April 2028. We need to be able to deploy on Bionic until then. Could you expand this change so that Bionic still works? Thanks!

2024-02-21 18:53 UTC, drencrom commented
Added check for `systemd-resolve` so it works with versions of systemd older than 239.

2024-02-21 19:46 UTC, nicolasbock approved these changes
Thanks!

2024-02-21 20:43 UTC, nicolasbock requested changes

2024-02-21 20:43 UTC, nicolasbock commented on common/helpers
>      echo "10.198.200.1"  # stsstack upstream dns
```suggestion
    # Use old systemd-resolve command if present
    if command -v systemd-resolve > /dev/null; then
        local server=$(systemd-resolve --status 2> /dev/null | sed --regexp-extended 's/\s*DNS Servers:\s+([[:digit:]]+)/\1/g;t;d'| head -n 1)
    else
        local server=$(resolvectl 2> /dev/null | sed --regexp-extended 's/\s*Current DNS Server:\s+([[:digit:]]+)/\1/g;t;d')
    fi
    (($? == 0)) && echo $server && return 0
    echo "10.198.200.1"  # stsstack upstream dns
```

2024-02-21 20:43 UTC, nicolasbock commented on common/helpers
>      echo "10.198.200.1"  # stsstack upstream dns
After more careful testing I realized that the output format is slightly different between the two commands.

2024-02-21 20:52 UTC, nicolasbock commented
> Thanks for the fix!
> 
> We are supporting Bionic / Queens until April 2028. We need to be able to deploy on Bionic until then. Could you expand this change so that Bionic still works? Thanks!

Just forget what I said there. It has nothing to do with your change :/

I would still like to keep support for Bionic, thanks for all of the updates!

2024-02-28 13:49 UTC, dosaboy approved these changes
lgtm

2024-02-28 14:07 UTC, nicolasbock approved these changes
Thanks!

2024-02-28 14:07 UTC, merged