Adds proxy and docker configuration for PS6
canonical/stsstack-bundles pull request #204
Opened 2024-07-11 19:44 UTC by sombrafam

2024-07-23 13:52 UTC, dnegreira commented on kubernetes/configure
> +if [[ $profile == "stsstack" ]]; then
We can drop these checks since stsstack is going away by the end of the week, lets make it compatible with ps6 only now.

2024-07-23 13:53 UTC, dnegreira commented on kubernetes/configure
> +
I would add an echo here telling users why/how to register.
Something along the lines:

`We need to add the docker credentials to your cloud in order not to be rate limited. You can create your account on https://hub.docker.com/".`

2024-07-23 14:11 UTC, nicolasbock requested changes

2024-08-14 05:37 UTC, lathiat commented
I have submitted an alternative PR which specifically takes care of configuring the contaienrd proxy, by using the containerd juju config options instead of the systemd override. I feel this method would mostly be preferable, with the exception that I don't auto-detect if we are in ProdStack6 or not:
https://github.com/canonical/stsstack-bundles/pull/218

For handling DockerHub authentication, there is also a charm option to set this which I think would also be preferred over the current method in this PR, unless I am missing something. I did not implement this in my PR. So perhaps if my PR gets merged, this one can be modified to handle only the Dockerhub authentication with some kind of convenience wrapper around setting the DockerHub username/password:
https://charmhub.io/containerd/configuration#custom_registries

2024-08-20 18:20 UTC, sombrafam commented
Dropping this one in favor of [Trents PR](https://github.com/canonical/stsstack-bundles/pull/218), that has a better solution.

2024-08-20 18:20 UTC, closed without merging